observeinc/terraform-aws-lambda

cloudwatch_logs_subscription/README.md
cloudwatch_logs_subscription/main.tf
cloudwatch_logs_subscription/variables.tf
cloudwatch_logs_subscription/versions.tf

Similar to our s3_bucket_subscription submodule, we now provide a
cloudwatch_logs_subscription submodule to simplify subscribing to our
lambda.

cloudwatch_logs_subscription: add helper submodule

---

cloudwatch_logs_subscription/README.md
cloudwatch_logs_subscription/main.tf
cloudwatch_logs_subscription/variables.tf

Calling the module with a large number of log groups will raise an error
due to the lambda policy overrunning AWS limits. This commit introduces
an option which replaces the default behavior of creating one permission
per log group, with a single permission allowing all log groups in an
account to invoke our lambda function.

cloudwatch_logs_subscription: introduce `allow_all_log_groups`

---

README.md
main.tf
variables.tf

Dead Letter Queue is required by certain security checks run by AWS security hub. This allows the function to get an existing sqs/sns queue as a dead Letter Queue.

Add dead_letter_queue_desitnation to the lambda function

---

snapshot/variables.tf

While the sdk declares an `elb` and `elbv2` service directory, the
underlying service name is `elasticloadbalancing`. This commit also
removes a superfluous prefix for route53.

snapshot: adjust action prefixes

---

README.md
main.tf
variables.tf

This commit adds an option to configure the `S3_CUSTOM_RULES`
environment variable used by the Observe lambda function.
This environment variable is a base64-encoded JSON array of "rules".
Each rule is composed of a regular expression and a map of HTTP headers.
The S3 URI of a created object will be sequentially compared against the
provided regular expressions. On the first match, we will apply the
associated HTTP headers to the outbound request towards Observe. If no
match is found, we fall back to inferred rules.

lambda: add lambda_s3_custom_rules variable

---

snapshot/variables.tf

Next lambda release will support Kinesis Data Streams, SNS Topics /
Subscriptions, and SQS Queues.

snapshot: extend default permissions

---

examples/s3_bucket/README.md
examples/s3_bucket/main.tf
examples/s3_bucket/variables.tf
s3_bucket_subscription/README.md
s3_bucket_subscription/main.tf
s3_bucket_subscription/variables.tf

It is common to subscribe multiple buckets to the same lambda. Doing so
through multiple modules increases the number of policies required, so
we might as well just allow users to pass in a list of bucket ARNs
rather than confine them to a single bucket per invocation.

feat: allow multiple buckets in s3_bucket_subscription

---

main.tf

We're deprecating v1/observations eventually.

fix: adjust collection endpoint

---

examples/cloudtrail/README.md
examples/cloudtrail/versions.tf
examples/s3_access_logs/README.md
examples/s3_access_logs/versions.tf
examples/s3_bucket/README.md
examples/s3_bucket/versions.tf
examples/vpc_config/README.md
examples/vpc_config/versions.tf

It appears the latest major version bump in AWS provider is not
compatible with some of the modules we use for our examples. Pin
accordingly.

fix: pin aws provider to < 4.0.0

---

main.tf

Allow unsetting reserved concurrency by setting value to be negative.

fix: support unreserved concurrency

---

README.md
examples/s3_access_logs/README.md
examples/s3_access_logs/versions.tf
examples/s3_bucket/README.md
examples/s3_bucket/versions.tf
examples/vpc_config/README.md
examples/vpc_config/versions.tf
main.tf
variables.tf
versions.tf

Migrate endpoint from `collect.observeinc.com` to
`{CUSTOMER_ID}.collect.observeinc.com`. In the process, datastream
tokens will be mandatory.

feat!: use per-customer collector endpoint

---

examples/cloudtrail/README.md
examples/cloudtrail/versions.tf
examples/s3_access_logs/README.md
examples/s3_access_logs/main.tf
examples/s3_access_logs/versions.tf
examples/s3_bucket/README.md
examples/s3_bucket/main.tf
examples/s3_bucket/versions.tf
examples/vpc_config/README.md
examples/vpc_config/versions.tf

Remove pin on AWS provider version. We needed this to protect against backward incompatible changes to S3 schemas, but those have since been backported to 3.75 branch.

fix: support aws provider 4.0+

---

README.md
examples/cloudtrail/README.md
examples/cloudtrail/variables.tf
examples/cloudtrail/versions.tf
examples/s3_access_logs/README.md
examples/s3_access_logs/variables.tf
examples/s3_access_logs/versions.tf
examples/s3_bucket/README.md
examples/s3_bucket/variables.tf
examples/s3_bucket/versions.tf
examples/vpc_config/README.md
examples/vpc_config/versions.tf
modules/cloudwatch_logs_subscription/README.md
modules/cloudwatch_logs_subscription/variables.tf
modules/cloudwatch_logs_subscription/versions.tf
modules/s3_bucket_subscription/README.md
modules/s3_bucket_subscription/variables.tf
modules/s3_bucket_subscription/versions.tf
modules/snapshot/README.md
modules/snapshot/variables.tf
modules/snapshot/versions.tf
variables.tf
versions.tf

This commit introduces the `nullable` argument to variable blocks. As a result of this change, the minimum provider version is bumped to 1.1.0.
The `nullable` argument allows callers of this module to override variables while still being able to fall back to our defaults, e.g.
```
variable "memory_size" {
type    = number
default = null
}
module "observe_lambda" {
source  = "observeinc/lambda/aws"
...
memory_size      = var.memory_size
}
```
Previously, passing `null` to `memory_size` in our module would error out, since the variable was expected to be a string. Now, passing `null` will cause terraform to fall back to the underlying default.

feat!: declare variables as nullable

---

examples/cloudtrail/main.tf
examples/s3_access_logs/main.tf
modules/s3_bucket_subscription/README.md
modules/s3_bucket_subscription/main.tf
modules/s3_bucket_subscription/variables.tf

This commit removes the deprecated `bucket` variable. Users should migrate to using `bucket_arns` instead.

fix(s3_bucket_subscription)!: remove `bucket` variable

---

modules/s3_bucket_subscription/README.md
modules/s3_bucket_subscription/main.tf
modules/s3_bucket_subscription/variables.tf

This commit changes the type of `bucket_arns` from `list(string)` to `set(string)`. This change makes the module robust against reordering, and naturally handles the case where duplicates are provided.
BREAKING CHANGE: migrating from previous versions may result in a race condition where terraform attempts to create a new `aws_s3_bucket_notification` prior to destroying the previous one. Re-running apply should successfully work around this issue.

feat(s3_bucket_subscription)!: convert `bucket_arns` to set

---

modules/s3_bucket_subscription/README.md
modules/s3_bucket_subscription/main.tf
modules/s3_bucket_subscription/variables.tf

This reverts commit a13b8fd75c8f1e882da0d2869a39acd06930a9e0.
A drawback of using `set` and `for_each` is that the keys must be known at apply-time in order to be used to address resource instances. This is a fundamental limitation:
https://developer.hashicorp.com/terraform/language/meta-arguments/for_each#limitations-on-values-used-in-for_each
In the context of this module, users pass in a collection a buckets. There is no obvious key that can be used to satisfy the current constraint for `for_each`. In the absence of an obvious candidate, users can enumerate a list and provide an index, at which point we're back to the same limitations that `count` has. At that point, it is better to revert and maintain backward compatibility with 1.x, and defer changes that attempt to retain stable …

feat(s3_bucket_subscription)!: revert `bucket_arns` to count

---

README.md
modules/cloudwatch_logs_subscription/README.md
modules/s3_bucket_subscription/README.md
modules/snapshot/README.md

The terraform provider requirements are already compiled by terraform-docs.
Module sources should point towards module registry.
Suggestions on how to contribute should be instead provided via CONTRIBUTING file.

docs: cleanup

---

modules/s3_bucket_subscription/main.tf

Currently on applying this module, users may hit the following error:
```
│ Error: putting S3 Bucket Notification Configuration: InvalidArgument: Unable to validate the following destination configurations
│       status code: 400, request id: 9DXT97CA77A3MTPX, host id: 9R+2v/kbrAp57YCPbITdTv4XUzLSq7rlzANk3rIQjRSNsKJxaA4wsPIgNNr8UmaAKNOaEPPkS0wO/A1mEOS4xw==
```
This appears to be due to a race between applying
`aws_lambda_permission` and `aws_s3_bucket_notification`. This commit ensures the S3 bucket has permission to invoke the lambda prior to assigning the lambda as a target for bucket notifications.

fix(s3_bucket_subscription): avoid race on subscription

---

.github/workflows/release.yaml

Allows releasers to trigger a dry-run and not actually push any of the release content. 
We are getting unexpected output when generating the release content/version and need to be able to debug this without creating live releases every time.
https://github.com/observeinc/terraform-aws-lambda/actions/runs/4326680129/jobs/7554389442#step:3:89
This can't be readily tested until it lands in `main`, because Actions won't process the workflow:
https://stackoverflow.com/questions/63362126/github-actions-how-to-run-a-workflow-created-on-a-non-master-branch-from-the-wo
You can dispatch on non-main branches, but the workflow content will be from the main branch:
```sh
gh workflow run 34990775 --ref test-push-false --field push=false
```
```
could not create workflow dispatch event: HTTP 422: …
```

chore(workflows): allow dry-run release

---

modules/cloudwatch_logs_subscription/README.md
modules/cloudwatch_logs_subscription/main.tf

This commit replaces the use of regexing ARNs with a data source construct.

refactor(cloudwatch_logs_subscription): replace regex with data.aws_arn

---

examples/s3_bucket/README.md
examples/s3_bucket/main.tf
examples/s3_bucket/outputs.tf
modules/s3_bucket/README.md
modules/s3_bucket/main.tf
modules/s3_bucket/outputs.tf
modules/s3_bucket/variables.tf
modules/s3_bucket/versions.tf

When configuring a bucket to trigger the Observe Lambda, there are many options that are commonly useful. This includes setting lifecycle rules or configuring permissions for services such as CloudWatch or CloudTrail to write to a prefix within the bucket.
Ths commit introduces the `s3_bucket` module, which is modelled after our current s3 bucket configuration in the `observeinc/collection/aws` module.

feat: add s3_bucket module

---

modules/cloudwatch_metrics/README.md
modules/cloudwatch_metrics/main.tf
modules/cloudwatch_metrics/variables.tf
modules/cloudwatch_metrics/versions.tf

This commit introduces a new submodule, `cloudwatch_metrics`. Similar to our API snapshot functionality, we set up a eventbridge rule that periodically triggers the lambda with a custom payload.
This payload tells the lambda what metrics to scrape for. Callers of this module can configure metric collection through the `period`, `interval`, `delay` and `filters` variables.
Users must provide a list of filters. Each filter must have a namespace, and an optional set of metric names and dimensions.

feat: support pulling from cloudwatch metrics

---

modules/snapshot/README.md
modules/snapshot/main.tf
modules/snapshot/variables.tf

This commit addresses nits uncovered in #58 which were also applicable to the snapshot module.

refactor(snapshot): address nits

---

.github/workflows/release.yaml

Reverts a temporary ref used to validate #55 without merging the upstream workflow

chore(workflow): revert release workflow to `@main`

---

modules/cloudwatch_metrics/main.tf
modules/cloudwatch_metrics/variables.tf

The schedule previously ran once an hour. It now should do what the interval variable says it does
I tested 1 minute, 5 minutes, and 3 hours

fix(cloudwatch_metrics): correct rule schedule expression

---

modules/cloudwatch_metrics/main.tf
modules/cloudwatch_metrics/variables.tf

PR #62 fixed our schedule expression to fire at the correct cadence, but subtly changed the time at which the rule would trigger. The use of the `rate` function ensures a rule will trigger at regular intervals from rule creation. Given the nature of the data we are collecting, we want rules to trigger aligned to fixed time boundaries (e.g. every minute, every hour). This commit reintroduces a correct cron expression.

fix(cloudwatch_metrics): revert to cron expression

---

examples/cloudtrail/versions.tf
examples/s3_access_logs/versions.tf
examples/s3_bucket/versions.tf
examples/vpc_config/versions.tf
modules/cloudwatch_logs_subscription/versions.tf
modules/s3_bucket/versions.tf
modules/s3_bucket_subscription/versions.tf
modules/snapshot/versions.tf
versions.tf

We no longer need terraform v0.12 compatibility, update syntax to appease tflint.

fix: update `required_providers` syntax

---

main.tf

We provide newer builds that can run on `provided.al2` for different architectures. These builds are under a GOARCH directory (e.g. `arm64/latest`). This commit identifies what runtime, handler and architecture to use based off of the version string.
Will defer switching the default for `lambda_version` to a future release.

feat: select runtime / arch based off version

---

main.tf

Makes explicit the implicit dependency between the Lambda and the CloudWatch log group with `name = format("/aws/lambda/%s", var.name)`. 
This pattern of hardcoding the Lambda CWL naming scheme with `depends_on` is used to have Terraform manage a CloudWatch Logs log group for a Lambda. Lambdas don't take a log group, but if one already exists with the right name they'll just use it. 
Without `depends_on`, there is a (very unlikely) race condition. If the Lambda managed to be created and get invoked before Terraform created the log group, Terraform will hit a conflict that only `import` can resolve.
This also ensures that during a `terraform destroy` that the graph is cleaned up in the reverse direction and the Lambda is destroyed before the log group. This is potentially important, …

fix: declare Lambda's dependency on log group

---

README.md
outputs.tf

Exposes the CloudWatch log group name as an output.
Allows callers of this module to wire up this log group with a filter to a Kinesis Firehose delivery stream, e.g.,:
https://github.com/observeinc/terraform-aws-kinesis-firehose/tree/main/modules/cloudwatch_logs_subscription
Currently, because the Lambda implicitly depends on this (even with #68), callers have to hardcode this `/aws/lambda/*` pattern. We should encapsulate the hack here.
`terraform validate` ensures this reference is valid and is sufficient proof that this works.

feat: add `log_group_name` output

---

README.md
examples/cloudtrail/README.md
examples/cloudtrail/main.tf
examples/cloudtrail/variables.tf
examples/s3_access_logs/README.md
examples/s3_access_logs/main.tf
examples/s3_access_logs/variables.tf
examples/s3_bucket/README.md
examples/s3_bucket/main.tf
examples/s3_bucket/variables.tf
examples/vpc_config/README.md
examples/vpc_config/main.tf
examples/vpc_config/variables.tf
main.tf
modules/cloudwatch_logs_subscription/README.md
modules/cloudwatch_metrics/README.md
modules/s3_bucket/README.md
modules/s3_bucket_subscription/README.md
modules/snapshot/README.md
variables.tf

This commit adds support for `collection_endpoint`, and deprecates both `customer` and `domain`.

feat: support OBSERVE_COLLECTION_ENDPOINT

---

README.md
variables.tf

Migrates off of Go 1.x runtime
Go 1.x is deprecated
Did a terraform apply and verified the Go runtime changed
```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
~ update in-place
Terraform will perform the following actions:
~ resource "aws_lambda_function" "this" {
~ architectures                  = [
- "x86_64",
+ "arm64",
]
~ handler                        = "main" -> "bootstrap"
id                             = "colin3"
~ last_modified                  = "2023-10-03T16:04:12.112+0000" -> (known after apply)
~ runtime                        = "go1.x" -> "provided.al2"
~ s3_key                         = "lambda/observer/latest.zip" -> "lambda/observer/arm64/latest.zip"
tags …
```

fix: Go 1.x runtime is deprecated

---

modules/snapshot/README.md
modules/snapshot/main.tf
modules/snapshot/versions.tf

We need to ensure we only invoke the snapshot lambda once we have the appropriate permission. Since we depend on the eventbridge target, we should ensure the target is only installed after the lambda permission has been configured.
We also update the version constraint on `aws` to reflect the use of `aws_lambda_invocation` which was only introduced in 3.72.0

fix: address snapshot race

---

README.md
variables.tf

update default aws snapshot lambda to 2gb and timeout to 120s
increase AWS Lambda reliability 
Tested in multiple customer high metadata cardinality environments

fix: CS-425 update default aws snapshot lambda to 2gb and timeout to 120s

---

README.md
main.tf
variables.tf

This commit adds support for encrypting the `OBSERVE_TOKEN` environment variable in transit.
Previously, this module accepted a `kms_key_arn` variable which affected all environment variables _at rest_. However, this still exposed the token in different contexts (e.g. AWS Config). We now allow reusing the KMS key to encrypt the variable, which gets decrypted by our lambda as of version `v1.0.20240501`.
This commit also introduces a subtle API change to the module. We pass in an object, `kms_key`, rather than a string, `kms_key_arn`. This is more friendly to the `count` operator, which cannot determine the value of an attribute until apply time.

feat: allow KMS encryption of token environment variable

---

modules/s3_bucket_subscription/main.tf

This pull request addresses `InvalidArgument` encountered creating the S3 bucket notification configuration. The error: 
```
Error: creating S3 Bucket (<BUCKET>) Notification: operation error S3: PutBucketNotificationConfiguration, https response error StatusCode: 400, RequestID: <ID>, HostID: <HOST>, api error InvalidArgument: Unable to
validate the following destination configurations
with module.<MODULE>.module.observe_lambda_s3_subscription.aws_s3_bucket_notification.notification[0],
on .terraform/modules/<MODULE>.observe_lambda_s3_subscription/modules/s3_bucket_subscription/main.tf line 20, in
resource "aws_s3_bucket_notification" "notification":
20: resource "aws_s3_bucket_notification" "notification" {
```
The error occurred because `aws_lambda_permission` and …

fix: Fix S3 Bucket Notification Configuration Validation Error OBSSD-612
